server:
  port: 10001
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,mappings,env,httptrace
mybatis:
  typeAliasesPackage: com.kubrick.sbt.web.entity
  mapperLocations: classpath:mapper/*.xml

xxl:
  job:
    admin:
      addresses: http://localhost:18888/xxl-job-admin
    executor:
      port: 18887
      appName: admin-jobs
      logretentiondays: 30

security:
  oauth2:
    ignoreUrls:
      - /api/common/ms
      - /login/**
